### ISSUE TITLE
google driver doesn't work

### ISSUE THREAD

**Issue by XIEBELL** [nguyenquivinhquang/Multi-camera-People-Tracking-With-Mixture-of-Realistic-and-Synthetic-Knowledge#5]
the link refer to “pretrained models and dataset ”，in google driver doesn't work，could you please upload it again?
thanks

**Comment by zef1611** [comment]
Hi, sorry for the late reply, I have been very busy lately so I cannot response anytime soon. The files in the google drive are deleted by my previous lab, however we no longer have access to that file either since we have all left the lab.

You can try to reproduce the model using the provided code from our repo, if possible I will try to train a new version and upload the weights.

Thank you for taking a big interested in our solution, hope you have a nice day.

**Comment by joaorulff** [comment]
Are you still planning to release the model weights?
